name: Simple Pipeline
on: 
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Run a simple script
        run: echo "The pipeline is running successfully!"
